version: '2'
services:
  rsyslog-docker:
    hostname: rsyslog-docker
    container_name: rsyslog-docker
    build: .
    image: rsyslog-docker
    ports:
      - "8514:8514/udp"
      - "10514:10514"
      - "8080:8080"
    #environment:
     # - "SUPERVISORD_LOGLEVEL=debug"
